package io.mosip.biosdk.client.constant;

/**
 * Utility class containing constant strings used for BioSDK client logging
 * configuration.
 *
 * This class provides static final string constants specifically designed for
 * the BioSDK client application's logging setup. These constants are intended
 * to be used with a logging framework like Logback to maintain consistency and
 * clarity in log messages.
 *
 * @since 1.0.0
 */
public class AppConstants {
	private AppConstants() {
		throw new IllegalStateException("AppConstants class");
	}

	/**
	 * Constant string representing the logger session ID used in BioSDK client
	 * logs.
	 *
	 * This value is typically used to identify a specific session or invocation of
	 * the BioSDK client application within the logs.
	 */
	public static final String LOGGER_SESSIONID = "BIO-SDK-CLIENT";

	/**
	 * Constant string representing the logger ID type used in BioSDK client logs.
	 *
	 * This value helps categorize logs generated by the BioSDK client application
	 * within the logging framework.
	 */
	public static final String LOGGER_IDTYPE = "BIO-SDK-CLIENT";
}